import React, { useState, useMemo } from "react";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Message } from "../types";
import { ThemeConfig } from "../themes";
import { AstraLogo } from "./AstraLogo";
import { CodeBlock } from "./CodeBlock";
import { AVAILABLE_MODELS } from "../config";
import { ModelNameLabel } from "./ModelNameLabel";
import {
  Copy,
  Check,
  User,
  AlertCircle,
  Maximize2,
  X,
  Sparkles,
} from "lucide-react";

interface ChatMessageProps {
  message: Message;
  theme: ThemeConfig;
  index?: number;
  onRetry?: () => void;
}

// Clean response content by removing any internal thought / reasoning traces
export function cleanDisplayContent(raw: string): string {
  if (!raw) return "";
  return raw
    // Strip XML-style thought tags (closed)
    .replace(
      /<(?:think|thinking|thought|thoughts|reasoning|antThinking|reflection)\b[^>]*>[\s\S]*?<\/(?:think|thinking|thought|thoughts|reasoning|antThinking|reflection)\s*>/gi,
      ""
    )
    // Strip unclosed thought tags (e.g. streaming or cut-off)
    .replace(
      /<(?:think|thinking|thought|thoughts|reasoning|antThinking|reflection)\b[^>]*>[\s\S]*$/gi,
      ""
    )
    // Strip orphaned closing thought tags
    .replace(
      /<\/(?:think|thinking|thought|thoughts|reasoning|antThinking|reflection)\s*>/gi,
      ""
    )
    // Strip details thought accordions if generated by upstream
    .replace(
      /<details\b[^>]*>[\s\S]*?<summary\b[^>]*>[\s\S]*?(?:thought|reasoning|thinking)[\s\S]*?<\/summary>[\s\S]*?<\/details>/gi,
      ""
    )
    // Strip code-fenced thought blocks (```thought ... ``` or ```thinking ... ```)
    .replace(/```(?:thought|thinking|reasoning)\b[\s\S]*?```/gi, "")
    .trim();
}

export function extractThinkingContent(raw: string): string {
  if (!raw) return "";
  const matches: string[] = [];
  const regex =
    /<(?:think|thinking|thought|thoughts|reasoning|antThinking|reflection)\b[^>]*>([\s\S]*?)(?:<\/(?:think|thinking|thought|thoughts|reasoning|antThinking|reflection)\s*>|$)/gi;
  let match;
  while ((match = regex.exec(raw)) !== null) {
    const text = match[1]?.trim();
    if (text) matches.push(text);
  }
  return matches.join("\n\n").trim();
}

const ChatMessageComponent: React.FC<ChatMessageProps> = ({ message, theme, index = 0 }) => {
  const isUser = message.role === "user";
  const [copied, setCopied] = useState(false);
  const [zoomImage, setZoomImage] = useState<string | null>(null);

  const formattedTime = new Date(message.timestamp).toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  });

  const entryNumber = String(index + 1).padStart(2, "0");

  const thinkingContent = useMemo(
    () => (isUser ? "" : extractThinkingContent(message.content)),
    [isUser, message.content]
  );
  const displayContent = useMemo(
    () => (isUser ? message.content : cleanDisplayContent(message.content)),
    [isUser, message.content]
  );
  const textToCopy = isUser ? message.content : displayContent;
  const hasTextToCopy = Boolean(textToCopy && textToCopy.trim().length > 0);

  const wordCount = useMemo(() => {
    if (message.isStreaming || !displayContent) return 0;
    return displayContent.trim().split(/\s+/).filter(Boolean).length;
  }, [displayContent, message.isStreaming]);

  const handleCopyMessage = async () => {
    if (!textToCopy) return;

    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(textToCopy);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
        return;
      }
    } catch {
      // Fallback below
    }

    // Fallback for non-secure contexts or older browsers
    try {
      const textArea = document.createElement("textarea");
      textArea.value = textToCopy;
      textArea.style.position = "fixed";
      textArea.style.opacity = "0";
      textArea.style.left = "-9999px";
      textArea.style.top = "-9999px";
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const successful = document.execCommand("copy");
      document.body.removeChild(textArea);
      if (successful) {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    } catch {
      // Fallback
    }
  };

  return (
    <>
      <div
        className={`group relative flex w-full my-2 ${
          isUser ? "justify-end" : "justify-start"
        }`}
        style={{ contentVisibility: "auto", containIntrinsicSize: "0 80px" }}
      >
        <div
          className={`relative flex items-start gap-3.5 transition-colors duration-150 ${
            isUser ? theme.message.userContainer : theme.message.assistantContainer
          }`}
        >
          {/* HUD Corner Reticles (Only in HUD mode) */}
          {theme.message.cornerBrackets && (
            <>
              <span className="absolute -top-1 -left-1 w-2.5 h-2.5 border-t border-l border-cyan-400 pointer-events-none" />
              <span className="absolute -top-1 -right-1 w-2.5 h-2.5 border-t border-r border-cyan-400 pointer-events-none" />
              <span className="absolute -bottom-1 -left-1 w-2.5 h-2.5 border-b border-l border-cyan-400 pointer-events-none" />
              <span className="absolute -bottom-1 -right-1 w-2.5 h-2.5 border-b border-r border-cyan-400 pointer-events-none" />
            </>
          )}

          {/* Avatar */}
          <div className="shrink-0 mt-0.5">
            {isUser ? (
              <div className={theme.message.userAvatar}>
                <User className="w-4 h-4" />
              </div>
            ) : (
              <div className={theme.message.assistantAvatar}>
                <AstraLogo size={20} />
              </div>
            )}
          </div>

          {/* Content Box */}
          <div className="flex-1 min-w-0">
            {/* Header with Name & Actions */}
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                {/* Optional Editorial Entry Index */}
                {theme.message.entryNumberPrefix && (
                  <span className="text-xs font-mono font-semibold opacity-60 uppercase tracking-wider">
                    [{theme.message.entryNumberPrefix}{entryNumber}]
                  </span>
                )}

                <span className={isUser ? theme.message.authorTextUser : theme.message.authorTextAssistant}>
                  {isUser ? "You" : "Orion Nebula GPT"}
                </span>

                {!isUser && (
                  <span className={theme.message.badge}>
                    <ModelNameLabel
                      name={
                        message.model
                          ? AVAILABLE_MODELS.find((m) => m.id === message.model)?.name || "Frontier"
                          : "Frontier"
                      }
                      shortOnMobile={true}
                    />
                  </span>
                )}

                <span className={theme.message.timestamp}>{formattedTime}</span>
              </div>
            </div>

            {/* User Attached Images (Multimodal Vision) */}
            {message.images && message.images.length > 0 && (
              <div className="flex flex-wrap gap-2.5 mb-3">
                {message.images.map((imgUrl, i) => (
                  <div
                    key={i}
                    onClick={() => setZoomImage(imgUrl)}
                    className="group/img relative rounded-xl overflow-hidden border border-slate-200 shadow-xs cursor-pointer hover:shadow-md transition-all max-w-[240px]"
                  >
                    <img
                      src={imgUrl}
                      alt={`Attached picture ${i + 1}`}
                      className="max-h-52 w-auto object-cover rounded-xl"
                    />
                    <div className="absolute inset-0 bg-slate-900/0 group-hover/img:bg-slate-900/25 transition-colors flex items-center justify-center">
                      <Maximize2 className="w-5 h-5 text-white opacity-0 group-hover/img:opacity-100 drop-shadow-md transition-opacity" />
                    </div>
                  </div>
                ))}
              </div>
            )}


            {/* Main Message Body */}
            <div className={isUser ? theme.message.bodyTextUser : theme.message.bodyTextAssistant}>
              {isUser ? (
                <div className="whitespace-pre-wrap">
                  {displayContent}
                </div>
              ) : (
                <div className="prose max-w-none">
                  {/* Thought Process Accordion */}
                  {thinkingContent && (
                    <div className="not-prose mb-3 rounded-xl border border-slate-200/80 dark:border-slate-700/80 bg-slate-50/80 dark:bg-slate-800/50 p-2.5 text-xs transition-all shadow-xs">
                      <details className="group" open={!displayContent}>
                        <summary className="cursor-pointer font-mono font-medium text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 select-none flex items-center justify-between">
                          <span className="flex items-center gap-1.5">
                            <Sparkles className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
                            <span>Thought Process</span>
                          </span>
                          <span className="text-[10px] text-slate-400 group-open:hidden uppercase font-semibold">Show reasoning</span>
                        </summary>
                        <div className="mt-2 pl-3 border-l-2 border-emerald-400/60 font-mono text-[11px] leading-relaxed whitespace-pre-wrap text-slate-600 dark:text-slate-300 max-h-60 overflow-y-auto">
                          {thinkingContent}
                        </div>
                      </details>
                    </div>
                  )}

                  {/* Thinking Pulse Indicator while waiting for initial text */}
                  {message.isStreaming && !displayContent && (
                    <div className="not-prose flex items-center gap-2 py-1 px-3 rounded-xl bg-slate-100/90 dark:bg-slate-800/80 border border-slate-200/80 dark:border-slate-700/80 text-slate-600 dark:text-slate-300 text-xs font-mono w-fit animate-pulse my-1 shadow-xs">
                      <span className="relative flex h-2 w-2">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                      </span>
                      <span className="tracking-wider uppercase font-semibold text-[11px]">Thinking...</span>
                    </div>
                  )}

                  {displayContent && (
                    <Markdown
                      remarkPlugins={[remarkGfm]}
                      components={{
                        code(props) {
                          const { className, children } = props;
                          const match = /language-(\w+)/.exec(className || "");
                          const isInline = !match && !String(children).includes("\n");

                          if (isInline) {
                            return (
                              <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-cyan-500/10 text-cyan-700 dark:text-cyan-300 border border-cyan-500/20">
                                {children}
                              </code>
                            );
                          }

                          return (
                            <CodeBlock
                              language={match ? match[1] : "text"}
                              code={String(children).replace(/\n$/, "")}
                            />
                          );
                        },
                        p({ children }) {
                          return <p className="mb-3 last:mb-0 leading-relaxed">{children}</p>;
                        },
                        ul({ children }) {
                          return <ul className="list-disc pl-5 mb-3 space-y-1">{children}</ul>;
                        },
                        ol({ children }) {
                          return <ol className="list-decimal pl-5 mb-3 space-y-1">{children}</ol>;
                        },
                        li({ children }) {
                          return <li className="leading-relaxed">{children}</li>;
                        },
                        h1({ children }) {
                          return <h1 className="text-lg font-bold tracking-tight mt-4 mb-2">{children}</h1>;
                        },
                        h2({ children }) {
                          return <h2 className="text-base font-bold tracking-tight mt-3 mb-2">{children}</h2>;
                        },
                        h3({ children }) {
                          return <h3 className="text-sm font-semibold tracking-tight mt-2 mb-1">{children}</h3>;
                        },
                        blockquote({ children }) {
                          return (
                            <blockquote className="border-l-2 border-cyan-500/50 pl-3 italic my-2 opacity-90">
                              {children}
                            </blockquote>
                          );
                        },
                      }}
                    >
                      {displayContent}
                    </Markdown>
                  )}
                </div>
              )}
            </div>

            {/* Error Banner */}
            {message.error && (
              <div className="mt-2.5 p-2.5 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-600 dark:text-rose-400 text-xs flex items-center gap-2">
                <AlertCircle className="w-4 h-4 shrink-0" />
                <span>{message.error}</span>
              </div>
            )}

            {/* Bottom Actions Bar (Quick Copy option at bottom of text) */}
            {hasTextToCopy && !message.isStreaming && (
              <div className="flex items-center justify-between mt-3 pt-2.5 border-t border-black/5 dark:border-white/10">
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleCopyMessage}
                    className={`inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-md transition-all active:scale-95 cursor-pointer ${theme.message.copyButton}`}
                    title="Copy message"
                  >
                    {copied ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
                        <span className="font-semibold text-emerald-600 dark:text-emerald-400">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy message</span>
                      </>
                    )}
                  </button>

                  {wordCount > 0 && (
                    <span className="text-[11px] font-mono opacity-50 select-none hidden xs:inline-block">
                      {wordCount} words
                    </span>
                  )}
                </div>

                <div className="text-[11px] font-mono opacity-50 select-none">
                  {formattedTime}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Fullscreen Image Zoom Lightbox Modal */}
      {zoomImage && (
        <div
          onClick={() => setZoomImage(null)}
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/75 backdrop-blur-md animate-in fade-in duration-150"
        >
          <div className="relative max-w-4xl max-h-[90vh] overflow-hidden rounded-2xl bg-white/10 p-2 shadow-2xl">
            <button
              onClick={() => setZoomImage(null)}
              className="absolute top-4 right-4 p-2 rounded-full bg-slate-900/80 hover:bg-rose-600 text-white transition-colors shadow-lg z-10"
              title="Close image"
            >
              <X className="w-5 h-5" />
            </button>
            <img
              src={zoomImage}
              alt="Enlarged attachment"
              className="max-h-[85vh] max-w-full object-contain rounded-xl"
            />
          </div>
        </div>
      )}
    </>
  );
};

export const ChatMessage = React.memo<ChatMessageProps>(
  ChatMessageComponent,
  (prev, next) => {
    return (
      prev.message.id === next.message.id &&
      prev.message.content === next.message.content &&
      prev.message.isStreaming === next.message.isStreaming &&
      prev.message.error === next.message.error &&
      (prev.message.images?.length || 0) === (next.message.images?.length || 0) &&
      prev.theme.id === next.theme.id &&
      prev.index === next.index
    );
  }
);
